name: Upload to JFrog Artifactory

on:
  workflow_dispatch:

jobs:
  upload-artifact:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: latest
        
      - name: Create text file and zip
        run: |
          echo "This is a test file." > testfile.txt
          zip testfile.zip testfile.txt

      - name: Remove Config
        run: |
          jf config remove matrix-artifactory --quiet || echo "No existing config to remove"
        
      - name: Configure JFrog CLI
        run: |
          jf config add matrix-artifactory \
            --artifactory-url="${{ vars.JFROG_URL }}" \
            --user="${{ secrets.JFROG_USER }}" \
            --password="${{ secrets.JFROG_PASSWORD }}" \
            --interactive=false \
            --default=true
      
      - name: Verify Config 
        run: |
          jf config show

      - name: Upload ZIP to Artifactory
        run: |
          jf rt upload "testfile.zip" "mx-test-repo/1.0.0/"
