name: Run Shell Script and Echo Var

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Shell Script
      run: |
        chmod +x ./var.sh
        ./var.sh

    - name: Echo var
      run: |
        echo "echo-in-yaml=$MY_VARIABLE"
        chmod +x ./var1.sh
        ./var1.sh
