name: Nightly Build for Main Branch

on:
  schedule:
    - cron: '05 12 * * *'
  workflow_dispatch:

jobs:
  fetch-branches:
    runs-on: ubuntu-latest
    outputs:
      main_branch: ${{ steps.get-branch.outputs.main_branch }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get main branch
        id: get-branch
        run: |
          MAIN_BRANCH=$(git ls-remote --heads origin | awk -F'/' '{print $3}' | grep '^main' | jq -R -s -c 'split("\n")[:-1]')
          echo "main_branch=$MAIN_BRANCH" >> $GITHUB_ENV
          echo "::set-output name=main_branch::$MAIN_BRANCH"

  build:
    needs: fetch-branches
    runs-on: ubuntu-latest
    if: needs.fetch-branches.outputs.main_branch == 'main'
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
      
      - name: Run build script
        run: |
          echo "Building main branch"
          cat test.txt
