name: Nightly Build for All Present Feature Branches

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature-')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display date and test.txt content
        run: |
          echo "Current date and time:"
          date
          echo "Displaying contents of test.txt:"
          cat test.txt
