name: nightly build for all present feature branches

on:
  schedule:
    - cron: '55 11 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature-')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display test.txt content
        run:
          date
          cat test.txt
